// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBILSqj3MBTb4duuYv_y7aup2N3AZ-XXGc',
    appId: '1:909262073828:web:944f88722ec33b136021f1',
    messagingSenderId: '909262073828',
    projectId: 'livetv-9a799',
    authDomain: 'livetv-9a799.firebaseapp.com',
    storageBucket: 'livetv-9a799.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeYZzQFDNxISWhmiuz4YfX-0wDsK6qb-U',
    appId: '1:909262073828:android:2b19e3a5beda80426021f1',
    messagingSenderId: '909262073828',
    projectId: 'livetv-9a799',
    storageBucket: 'livetv-9a799.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvT9wFX07cdXkR3sciuINJnqviFXstSuA',
    appId: '1:909262073828:ios:4d60dbc02fc692946021f1',
    messagingSenderId: '909262073828',
    projectId: 'livetv-9a799',
    storageBucket: 'livetv-9a799.appspot.com',
    iosBundleId: 'com.example.onlinetv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvT9wFX07cdXkR3sciuINJnqviFXstSuA',
    appId: '1:909262073828:ios:4b21c66ec14946a86021f1',
    messagingSenderId: '909262073828',
    projectId: 'livetv-9a799',
    storageBucket: 'livetv-9a799.appspot.com',
    iosBundleId: 'com.example.onlinetv.RunnerTests',
  );
}
